name: Build Gradle project

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with: 
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - name: CD to project directory
      run: cd esop-trading
    - name: Run build with Gradle Wrapper
      run: cd esop-trading && ./gradlew build
    - name: Run tests with Gradle Wrapper
      run: cd esop-trading && ./gradlew test