name: Build Gradle project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2

      - name: Validate gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK 19
        uses: actions/setup-java@v2
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

  test-project:
    needs: build-project
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./esop-trading
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2

      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      - name: Run tests with Gradle Wrapper
        run: ./gradlew test

  deploy-project:
    needs: [ build-project, test-project ]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./esop-trading
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2

      - name: Create shadow jar
        run: ./gradlew shadowJar

