name: Build Gradle project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-project:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./esop-trading
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Validate gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      - name: Run tests with Gradle Wrapper
        run: ./gradlew test

  build-project:
    needs: test-project
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./esop-trading
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Create shadow jar
        run: ./gradlew shadowJar

      - name: Setup pem file
        run: echo '${{ secrets.KEY }}' > file.pem
          | chmod 400 file.pem

      - name: Run scp to get the jar to instance
        run: scp -o StrictHostKeyChecking=no -i file.pem  "./esop-trading/build/libs/esop-trading-0.1-all.jar" ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/

      - name: execute remote commands
        run: ssh -o StrictHostKeyChecking=no -i file.pem ${{ secrets.USERNAME }}@${{ secrets.HOST }} '
          nohup java -jar ./esop-trading/build/libs/esop-trading-0.1-all.jar > /dev/null 2>&1&'


