name: Build Gradle project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-project:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./esop-trading
    steps:
      - name: Clone repo
        run: git fetch --depth 1 origin $GITHUB_REF

      - name: Validate gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      - name: Run tests with Gradle Wrapper
        run: ./gradlew test

      - name: Checkout project sources
        uses: actions/checkout@v2

      - name: Create shadow jar
        run: ./gradlew shadowJar

      - name: Copy jar to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          username: ${{ secrets.USERNAME }}
          port: 22
          source: "./esop-trading/build/libs/esop-trading-0.1-all.jar"
          target: "~/"

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          username: ${{ secrets.USERNAME }}
          port: 22
          script: "nohup java -jar ./esop-trading/build/libs/esop-trading-0.1-all.jar > /dev/null 2>&1&"


